#!/bin/sh

help () {
	echo ""
	echo "anapal's todo list"
	echo "	todo [OPTIONS]"
	echo ""
	echo "todo-list options:"
	echo "	edit, -e     edit the list"
	echo "	help, -h,    show this help message"

}

case $1 in
	"edit") vim ~/.todo-list ;;
	"-e") vim ~/.todo-list ;;
	"help") help ;;
	"-h") help ;;
	*) cat /home/anapal/.todo-list ;;
esac

